name: CI

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Replace with your desired Go version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...  # Replace with your test command
